
FROM node:16 AS build
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm install
COPY . /app/
RUN npm run build

FROM nginx:latest
COPY --from=build /dist/* /usr/share/nginx/html/

EXPOSE 8000

CMD ["nginx","-g","daemon off;"]